### ISSUE TITLE
Support jcenter?

### ISSUE THREAD

**Issue by yongjhih** [cesarferreira/alfi#1]

**Comment by cesarferreira** [comment]
@yongjhih  which libraries are you missing? can you give me an example

**Comment by yongjhih** [comment]
http://jcenter.bintray.com/com/infstory/rxparse/1.0.0/

**Comment by cesarferreira** [comment]
Since jcenter() is a superset of mavenCentral() and there is an API https://bintray.com/docs/api, I'll look into it

**Comment by yongjhih** [comment]
Thanks.

**Comment by wasabeef** [comment]
:+1:

**Comment by jenzz** [comment]
+1

**Comment by amouly** [comment]
+1
Great app!

**Comment by intrications** [comment]
Any update on this? It seems more libraries are now only on jcenter.

**Comment by ivan-leschinsky** [comment]
@intrications, @amouly , @jenzz , @wasabeef , @yongjhih,  I'm working on implementing this now

**Comment by jenzz** [comment]
@ivan-leschinsky, I can see you have added support for searching on JCenter in your fork.
Do you mind creating a pull requests so we can get this merged and published as a new release?

**Comment by ivan-leschinsky** [comment]
@jenzz I'm sorry, but actually I haven't time to continue work on it. And JCenter requires API token to interact with it, as I've investigated. So I don't know when I'll end with it.

https://bintray.com/docs/api/
I also didn't find any API call to find repository by name or package name

If you could make some API call to that server with any successful results - let me know please. I'll happy to add it to the all another sources.

**Comment by ivan-leschinsky** [comment]
Actually I found how to do that, after you've reminded me :smile: 
I think that it will be done soon

**Comment by ivan-leschinsky** [comment]
@intrications, @amouly , @jenzz , @wasabeef , @yongjhih 
Bintray requires authentication to search the repos. Are you agree to use alfi with your own API key for jCenter? Or as second option I could hard-code some api keys that you would give me to use them random.

**Comment by yongjhih** [comment]
Agree. To allow load bintray token from env var or config file.

**Comment by ivan-leschinsky** [comment]
Now I've getting something like that
![vano-mbp-2015 11 26-12-48-11](https://cloud.githubusercontent.com/assets/4127186/11419976/0ef305d2-943c-11e5-9ad7-969d99888ba3.jpg)

**Comment by cesarferreira** [comment]
@yongjhih thank @ivan-leschinsky for this :) 
![screenshot 2015-11-27 15 21 53](https://cloud.githubusercontent.com/assets/277426/11444100/b1c76f58-951a-11e5-8f12-298f87773e39.png)

good job
