### ISSUE TITLE
gem install alfi error

### ISSUE THREAD

**Issue by hlllmr1314** [cesarferreira/alfi#15]
Hi ：
$ sudo gem install alfi
Building native extensions.  This could take a while...
ERROR:  Error installing alfi:
	ERROR: Failed to build gem native extension.

        /usr/bin/ruby1.9.1 extconf.rb
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- mkmf (LoadError)
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from extconf.rb:1:in `<main>'

Gem files will remain installed in /var/lib/gems/1.9.1/gems/json-2.0.3 for inspection.

**Comment by cesarferreira** [comment]
The min ruby required is 2.0.0 `spec.required_ruby_version = '>= 2.0.0'`

Please update your ruby (I don't know how rubygems let's you install a gem that's below the requirements)
