### ISSUE TITLE
Can't install in MacOS Sierra

### ISSUE THREAD

**Issue by merlin-zaraza** [cesarferreira/alfi#16]
`sudo gem install alfi`
`ERROR:  While executing gem ... (Errno::EPERM)`
`    Operation not permitted - /usr/bin/bundle`

`ruby --version`
`ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]`

**Comment by ivan-leschinsky** [comment]
@merlin-zaraza Try to install it without `sudo`. I think you don't need this lib for the root user.
I use `rvm` and created global gemset and wrapper for this gem. https://rvm.io/deployment/god

**Comment by merlin-zaraza** [comment]
@ivan-leschinsky here is output when I try without sudo:
`gem install alfi`
`ERROR:  While executing gem ... (Gem::FilePermissionError)`
`    You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory.`

Don't want to use `rvm`

**Comment by AlaaZarifa** [comment]
@merlin-zaraza  try installing it like this =>  `gem install alfi /usr/local/bin cocoapods`

**Comment by merlin-zaraza** [comment]
@AlaaZarifa I've installed latest ruby with brew and this solved my problem.
