### ISSUE TITLE
Error installing alfi using ruby 2.5.0

### ISSUE THREAD

**Issue by UltramanTIGA** [cesarferreira/alfi#20]
$ gem install alfi
Building native extensions. This could take a while...
ERROR:  Error installing alfi:
	ERROR: Failed to build gem native extension.

    current directory: /usr/local/lib/ruby/gems/2.5.0/gems/json-2.0.4/ext/json/ext/generator
/usr/local/opt/ruby/bin/ruby -r ./siteconf20180225-2421-jxjrmi.rb extconf.rb
creating Makefile

current directory: /usr/local/lib/ruby/gems/2.5.0/gems/json-2.0.4/ext/json/ext/generator
make "DESTDIR=" clean
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

current directory: /usr/local/lib/ruby/gems/2.5.0/gems/json-2.0.4/ext/json/ext/generator
make "DESTDIR="
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

make failed, exit code 1

Gem files will remain installed in /usr/local/lib/ruby/gems/2.5.0/gems/json-2.0.4 for inspection.
Results logged to /usr/local/lib/ruby/gems/2.5.0/extensions/x86_64-darwin-16/2.5.0/json-2.0.4/gem_make.out

**Comment by cesarferreira** [comment]
```

**Comment by cesarferreira** [comment]
```
~/code/github/alfi master
❯ ruby -v              
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin17]

~/code/github/alfi master 1m 2s
❯ gem install alfi  
Fetching: alfi-0.6.0.gem (100%)
Successfully installed alfi-0.6.0
Parsing documentation for alfi-0.6.0
Installing ri documentation for alfi-0.6.0
Done installing documentation for alfi after 0 seconds
1 gem installed
```

hmm, worked fine here

**Comment by UltramanTIGA** [comment]
I try again just now. And it install success..
emm, it is really strange
