### ISSUE TITLE
Gradle Kotlin-DSL has double quotes and parenthesis

### ISSUE THREAD

**Issue by jmfayard** [cesarferreira/alfi#21]
Can you add an option `--format=[kotlin|groovy]`  to generate the dependency information compatible with `build.gradle` for groovy and `build.gradle.kts` for kotlin? 

Ideally calling with no format argument should use the previous value

--format=kotlin would be like this:

```
dependencies {
  implementation("com.squareup.picaso:picaso:2.5.2")
}
```

**Comment by cesarferreira** [comment]
it doesn't work without `()` anymore?

**Comment by jmfayard** [comment]
Correct, 

- in kotlin `build.gradle.kts`, it doesn't work without `()` (implementation is a normal extension method)
- in kotlin `build.gradle.kts`, it doesn't work with simple quotes (like in java)
- in groovy `build.gradle, `implementation("com.squareup.picaso:picaso:2.5.2")` with parenthesis and double quotes is actually an accepted syntax. 

So actually, instead of having an option `--format=kotlin|groovy`, we could just change the dependency format to `implementation("com.squareup.picaso:picaso:2.5.2")` and be compatible with both!

![image](https://user-images.githubusercontent.com/459464/46345314-5e7b1300-c644-11e8-9283-e4e6a3ad0623.png)

**Comment by jmfayard** [comment]
@cesarferreira would you be interested by a pull-request where I change the output so that it works both in a `build.gradle` and a `build.gradle.kts` file?

```diff
dependencies {
-  implementation 'com.squareup.picaso:picaso:2.5.2'
+  implementation("com.squareup.picaso:picaso:2.5.2")
}
```

**Comment by cesarferreira** [comment]
Yes please @jmfayard

**Comment by jmfayard** [comment]
@cesarferreira done! The first line of ruby I ever wrote, hopefully not wrong :)

**Comment by cesarferreira** [comment]
It works, thanks for the PR

**Comment by cesarferreira** [comment]
btw @jmfayard love the idea on your lib https://github.com/jmfayard/gradle-kotlin-dsl-libs
