### ISSUE TITLE
Can't install on Mac OSX El Capitain

### ISSUE THREAD

**Issue by JulienDev** [cesarferreira/alfi#4]
Hi,

Mac OSX does not allow anymore to install anything in /usr/bin/ so we wan't install Alfi anymore :(

[ ~ ] sudo gem install alfi
ERROR:  While executing gem ... (Errno::EPERM)
    Operation not permitted - /usr/bin/alfi

Could you release a new version which installs the binary into /usr/local/bin/ ?

Thanks !

**Comment by cesarferreira** [comment]
Hey mate,
it looks like `ruby` still thinks that the executables should be in /usr/bin, did you re-installed ruby, uninstalled alfi and tried to reinstall?

if you check https://github.com/cesarferreira/alfi/blob/master/alfi.gemspec you can see that I tell the gem that the executable files are in the bin/ folder, I don't tell ruby where to put them.

I'll try to install El Capitan tomorrow and check this out anyway

**Comment by ivan-leschinsky** [comment]
I'm using El Capitan about 4 months. There is no problem with gem or OS X. I am using rvm for ruby and default gemset which works for all system.

**Comment by cesarferreira** [comment]
just did a fresh install With _El capitan_
![screenshot 2015-10-02 17 15 24](https://cloud.githubusercontent.com/assets/277426/10251533/3bdbc96e-6929-11e5-9b56-2fbfd1d023c1.png)

**Comment by JulienDev** [comment]
Hi,

Indeed, I also did a fresh install with el capitan and it's now working. This bug seems to affect some users who did few OSX updates without doing fresh installs. Sorry for the report...

**Comment by cesarferreira** [comment]
No problem mate :) thanks for reporting!
