### ISSUE TITLE
missing OptionParser

### ISSUE THREAD

**Issue by wilsonssss** [cesarferreira/alfi#6]
```
/Library/Ruby/Gems/2.0.0/gems/alfi-0.4.1/lib/alfi/cli.rb:34:in `create_options_parser': uninitialized constant Alfi::Cli::OptionParser (NameError)
    from /Library/Ruby/Gems/2.0.0/gems/alfi-0.4.1/lib/alfi/cli.rb:10:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/alfi-0.4.1/bin/alfi:5:in `<top (required)>'
    from /usr/local/bin/alfi:23:in `load'
    from /usr/local/bin/alfi:23:in `<main>'
```

resolved by adding 

```
require 'optparse'
include OptionParser::Arguable
```

to /Library/Ruby/Gems/2.0.0/gems/alfi-0.4.1/lib/alfi/cli.rb

**Comment by ivan-leschinsky** [comment]
Will be fixed soon.

ср, 9 дек. 2015 г., 6:47, WilsonL notifications@github.com:

**Comment by ivan-leschinsky** [comment]
@cesarferreira, could you please add this to the `cli.rb` and release the version?

**Comment by VibeMage** [comment]
I had the same problem,but i don't know how to add it to the `cli.rb`.
I want to use alfi.
thx.

**Comment by cesarferreira** [comment]
Sorry guys, I was away for a few days, does this fixes your issue @wilsonssss and @jbxkuang ?

install the 0.4.2 version please

**Comment by VibeMage** [comment]
@cesarferreira 
thx,0.4.2 is success.^_^

**Comment by cesarferreira** [comment]
awesome :)

**Comment by wilsonssss** [comment]
fixed.
