### ISSUE TITLE
cannot install by gem

### ISSUE THREAD

**Issue by lawrencewqy** [cesarferreira/alfi#7]
ERROR:  Could not find a valid gem 'alfi' (>= 0), here is why:
          Unable to download data from http://ruby.taobao.org/ - bad response Not Found 404 (http://ruby.taobao.org/specs.4.8.gz)

**Comment by cesarferreira** [comment]
Hey, I never heard of ruby taobao before, I uploaded to rubygems, maybe that's some kind of mirror?

**Comment by lawrencewqy** [comment]
yes ,it's a mirror,i reset sources to rubygems and install alfi success , thank you.
